[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
strict = true
check_untyped_defs = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 100

[tool.pycln]
expand_stars = true
verbose = true
all = true
no_gitignore = false
